EbonneeLovesCodeSite/EbonneeLovesCodeSite/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import index
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from django.conf.urls import url
# from blog.views import about

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', index, name='index'),
    # path('about', about, name='about'),
    path('', include('blog.urls', namespace='blog'))
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

EbonneeLovesCodeSite/blog/urls.py
from django.urls import path
# from .views import
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'), 
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('work/', views.work, name='work'),
    path('single_post/<int:id>/', views.single_post, name='single-post'),
    path('index/', views.index, name='home'),
]

EbonneeLovesCodeSite/blog/models.py
from django.db import models
from django.contrib.auth. models import User

# Create your models here.
STATUS = (
    (0, "Draft"),
    (1, "Publish")
)


class Post(models.Model):
    title = models.CharField(max_length=400, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE, related_name= 'blog_posts')
    updated_on = models.DateField(auto_now= True)
    created_on = models.DateField(auto_now_add= True)
    content = models.TextField()
    status = models.IntegerField(choices=STATUS, default=0)

    def __str__(self):
        return self.title

EbonneeLovesCodeSite/blog/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=70)
    email = forms.CharField(max_length=120)
    website = forms.CharField(max_length=200)
    where_from = forms.CharField(max_length=50)
    subjects = (
        ("Web Design & Development", "Web Design & Development"),
        ("Mobile Website", "Mobile Website"),
        ("I Want to General Talk", "I Want to General Talk"),
        ("Other", "Other"),
    )
    subject = forms.ChoiceField(choices = subjects)
    message = forms.CharField(max_length=600)

EbonneeLovesCodeSite/blog/views.py
from django.shortcuts import render
from django.template.loader import render_to_string
from django.http import HttpResponse
from django.template import loader
from .models import Post
from django.core.mail import send_mail
from .forms import ContactForm
#import models

# Create your views here.

def index(request):
    posts = Post.objects.all()
    context = {
        "posts": posts
    }

    return render(request, 'index.html', context)

def single_post(request, id):
    post = Post.objects.get(id=id)
    context = {
        'post': post
    }
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def contact(request):
    if request.method == "POST":
        
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            website = form.cleaned_data['website']
            where_from = form.cleaned_data['where_from']
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            print(where_from)
        # send an email
        message_main = f'name: {name} \n email: {email} \n website: {website} \n message: {message} '
        send_mail(
            subject, # subject
            message_main, # message
            '', # from email
            ['ebonnee.hoggard@gmail.com'], # To email
        )
    else:
        form = ContactForm()
    context = {
        'form': form
    }
    return render(request, 'contact.html', context)

def work(request):
    return render(request, 'work.html')

EbonneeLovesCodeSite/blog/templates/about.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}

  <head>
    
    <!-- Meta Tag -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <!-- SEO -->
    <meta name="description" content="150 words">
    <meta name="author" content="uipasta">
    <meta name="url" content="http://www.yourdomainname.com">
    <meta name="copyright" content="company name">
    <meta name="robots" content="index,follow">
    
    
    <title>DevBlog - Personal Blog Template</title>
    
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon/favicon.ico' %}">
    <link rel="apple-touch-icon" sizes="144x144" type="image/x-icon" href="{% static 'images/favicon/apple-touch-icon.png' %}">
    
    <!-- All CSS Plugins -->
    <link rel="stylesheet" type="text/css" href="/static/css/plugin.css">
    
    <!-- Main CSS Stylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    
    <!-- Google Web Fonts  -->
    <link rel="stylesheet" 
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0-12/css/all.min.css" 
          integrity="sha512-pn4RwKFKdSvaTRSYO5WIUGz89e1tJvWWUGRIBym1/k467SuMMjKKw/X5TXJYp2+WLmHumHivCJ2JAJppXF9SoA==" 
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'https://fonts.googleapis.com/css?family' %}=Poppins:400,300,500,600,700">
    
    
    <!-- HTML5 shiv and Respond.js support IE8 or Older for HTML5 elements and media queries -->
    <!--[if lt IE 9]>
	   <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
	   <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    

  </head>

 <body>

	
     
	 <!-- Preloader Start -->
     <div class="preloader">
	   <div class="rounder"></div>
      </div>
      <!-- Preloader End -->
      
      
    
    
    <div id="main">
        <div class="container">
            <div class="row">
            	
               
                 
                 <!-- About Me (Left Sidebar) Start -->
                 <div class="col-md-3">
                   <div class="about-fixed">
                    
                     <div class="my-pic">
                      <img src="{% static 'images/pic/my-pic.jpg' %}" alt="">
                      <a href="javascript:void(0)" class="collapsed" data-target="#menu" data-toggle="collapse">
                          <i class="fas fa-bars icon-menu menu"></i>
                        </a>
                         <div id="menu" class="collapse">
                           <ul class="menu-link">
                               <li><a href="/about">About</a></li>
                               <li><a href="/work">Work</a></li>
                               <li><a href="/contact">Contact</a></li>
                            </ul>
                         </div>
                        </div>
                      
                      
                      
                      <div class="my-detail">
                    	
                        <div class="white-spacing">
                            <h1>Ebonnee Hoggard</h1>
                            <span>Web Developer</span>
                        </div> 
                       
                       <ul class="social-icon">
                         <li><a href="#" target="_blank" class="facebook"><i class="fab fa-facebook"></i></a></li>
                         <li><a href="https://www.linkedin.com/in/ebonnee-hoggard-b2338124/" target="_blank" class="linkedin"><i class="fab fa-linkedin"></i></a></li>
                         <li><a href="https://github.com/EHoggard" target="_blank" class="github"><i class="fab fa-github"></i></a></li>
                        </ul>

                    </div>
                  </div>
                </div>
                <!-- About Me (Left Sidebar) End -->
                
                
                
                
                 
                 <!-- About Me (Right Sidebar) Start -->
                 <div class="col-md-9">
                    <div class="col-md-12 page-body">
                    	<div class="row">
                    		
                            
                            <div class="sub-title">
                           		<h2>About Me</h2>
                                <a href="/contact"><i class="fas fa-envelope"></i></a>
                             </div>
                            
                            
                            <div class="col-md-12 content-page">
                              <div class="col-md-12 blog-post">
                            	
                                
                                <!-- My Intro Start -->
                                <div class="post-title margin-bottom-30">
                                    <h1>Hi, I am <span class="main-color">Ebonnee Hoggard</span></h1>
                                    
                                    <ul class="knowledge">
                                      <li class="bg-color-4">Web Developer</li>
                                      <li class="bg-color-6">Freelancer</li>
                                      <li class="bg-color-5">Consultant</li>
                                     </ul>
                                     
                                   </div>
                                   <!-- My Intro End -->
                                    
                                    
                                    <p>I have been designing websites since 2021.  Learning new and exciting things on web development is now a new passion of mine and I cannot wait to share my new skill set.  My next big project will be to work on a website for ex female prison inmates transitioning back to the outside world.</p>
                          
                                  <!-- My Service Start -->
                                  <div class="post-title">
                                    <h1>My <span class="main-color">Services</span></h1> 
                                   </div>
                                   
                                  <div class="list list-style-2 margin-top-30">
                                    <ul>
                                      <li>Website Development</li>
                                      <li>Online Software Development</li>
                                      <li>E-commerce Development</li>
                                     </ul>
                                   </div>
                                   <!-- My Service End --> 
                                  
                                </div>  
                                
                                  <div class="col-md-12 text-center">
                                    <a href="contact.html" data-toggle="tooltip" data-placement="top" title="Visit on my contact page for hire me." class="load-more-button">Hire</a>
                                   </div>
                                  
                             </div>
                              
                         </div>
                         
                        
                        

                           
                           
                         </div>
                     
                     
                       
                       <!-- Footer Start -->
                       <div class="col-md-12 page-body margin-top-50 footer">
                          <footer>
                          <ul class="menu-link">
                               <li><a href="/index">Home</a></li>
                               <li><a href="/about">About</a></li>
                               <li><a href="/work">Work</a></li>
                               <li><a href="/contact">Contact</a></li>
                            </ul>
                            
                          <p>© Copyright 2016 DevBlog. All rights reserved</p>
						  
						  
						  <!-- UiPasta Credit Start -->
                          <div class="uipasta-credit">Design By <a href="http://www.uipasta.com" target="_blank">UiPasta</a></div>
                          <!-- UiPasta Credit End -->
						  
                           
                         </footer>
                       </div>
                       <!-- Footer End -->
                     
                     
                  </div>
                  <!-- About Me (Right Sidebar) End -->
                
            </div>
         </div>
      </div>
    
      
    
    
    
    <!-- Back to Top Start -->
    <a href="#" class="scroll-to-top"><i class="fa fa-long-arrow-up"></i></a>
    <!-- Back to Top End -->
    
    
    <!-- All Javascript Plugins  -->
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugin.js' %}"></script>
    
    <!-- Main Javascript File  -->
    <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>

    
   </body>
 </html>

EbonneeLovesCodeSite/blog/templates/index.html
<!DOCTYPE html>
<html lang="en">

  <head>
    
    <!-- Meta Tag -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <!-- SEO -->
    <meta name="description" content="150 words">
    <meta name="author" content="uipasta">
    <meta name="url" content="http://www.yourdomainname.com">
    <meta name="copyright" content="company name">
    <meta name="robots" content="index,follow">
    
    
    <title>DevBlog - Personal Blog Template</title>

    {% load static %}
    
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon/favicon.ico' %}">
    <link rel="apple-touch-icon" sizes="144x144" type="image/x-icon" href="images/favicon/apple-touch-icon.png">
    
    <!-- All CSS Plugins -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/plugin.css' %}">
    
    <!-- Main CSS Stylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    
    <!-- Google Web Fonts  -->
    <link rel="stylesheet" 
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0-12/css/all.min.css" 
          integrity="sha512-pn4RwKFKdSvaTRSYO5WIUGz89e1tJvWWUGRIBym1/k467SuMMjKKw/X5TXJYp2+WLmHumHivCJ2JAJppXF9SoA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:400,300,500,600,700">
    
    
    <!-- HTML5 shiv and Respond.js support IE8 or Older for HTML5 elements and media queries -->
    <!--[if lt IE 9]>
	   <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
	   <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    

  </head>

 <body>

	
     
	 <!-- Preloader Start -->
     <div class="preloader">
	   <div class="rounder"></div>
      </div>
      <!-- Preloader End -->
      
      
    
    
    <div id="main">
        <div class="container">
            <div class="row">
            	
               
                 
                 <!-- About Me (Left Sidebar) Start -->
                 <div class="col-md-3">
                   <div class="about-fixed">
                    
                     <div class="my-pic">
                        <img src="{% static 'images/pic/my-pic.jpg' %}" alt="">
                        <a href="javascript:void(0)" class="collapsed" data-target="#menu" data-toggle="collapse">
                          <i class="fas fa-bars icon-menu menu"></i>
                        </a>

                         <div id="menu" class="collapse">
                           <ul class="menu-link">
                               <li><a href="/about">About</a></li>
                               <li><a href="/work">Work</a></li>
                               <li><a href="/contact">Contact</a></li>
                            </ul>
                         </div>
                        </div>
                      
                      
                      
                      <div class="my-detail">
                    	
                        <div class="white-spacing">
                            <h1>Ebonnee Hoggard</h1>
                            <span>Web Developer</span>
                        </div> 
                       
                       <ul class="social-icon">
                         <li><a href="#" target="_blank" class="facebook"><i class="fab fa-facebook"></i></a></li>
                         <li><a href="https://www.linkedin.com/in/ebonnee-hoggard-b2338124/" target="_blank" class="linkedin"><i class="fab fa-linkedin"></i></a></li>
                         <li><a href="https://github.com/EHoggard" target="_blank" class="github"><i class="fab fa-github"></i></a></li>
                        </ul>

                    </div>
                  </div>
                </div>
                <!-- About Me (Left Sidebar) End -->
                
                
                
                
                 
                 <!-- Blog Post (Right Sidebar) Start -->
                 <div class="col-md-9">
                    <div class="col-md-12 page-body">
                    	<div class="row">
                    		
                            
                            <div class="sub-title">
                           		<h2>My Blog</h2>
                                <a href="/contact"><i class="fas fa-envelope"></i></a>
                             </div>
                            
                            
                            <div class="col-md-12 content-page">
                            	
                                {% for post in posts %}

                                <!-- Blog Post Start -->
                                <div class="col-md-12 blog-post">
                                    <div class="post-title">
                                      <a href="single.html"><h1>{{post.title}} </h1></a>
                                    </div>  
                                    <div class="post-info">
                                    	<span>{{post.created_on}} / by <a href="#" target="_blank">{{post.author}}</a></span>
                                    </div>  
                                    <p>{{post.content}}</p>                          			
                                    <a href="{% url 'blog:single-post' post.id %}" class="button button-style button-anim fa fa-long-arrow-right"></a>
                                </div>
                                <!-- Blog Post End -->

                                {% endfor %}
                                
                                
                                
                                
                                
                                
                                
                                
                                <div class="col-md-12 text-center">
                                 <a href="javascript:void(0)" id="load-more-post" class="load-more-button">Load</a>
                                 <div id="post-end-message"></div>
                                </div>
                                
                             </div>
                              
                         </div>
                         
                        
                        

                           
                         </div>
                     
                     
                       <!-- Footer Start -->
                       <div class="col-md-12 page-body margin-top-50 footer">
                          <footer>
                          <ul class="menu-link">
                               <li><a href="/index">Home</a></li>
                               <li><a href="/about">About</a></li>
                               <li><a href="/work">Work</a></li>
                               <li><a href="/contact">Contact</a></li>
                            </ul>
                            
                          <p>© Copyright 2016 DevBlog. All rights reserved</p>
						  
						  
						  <!-- UiPasta Credit Start -->
                          <div class="uipasta-credit">Design By <a href="http://www.uipasta.com" target="_blank">UiPasta</a></div>
                          <!-- UiPasta Credit End -->

                           
                         </footer>
                       </div>
                       <!-- Footer End -->
                     
                     
                  </div>
                  <!-- Blog Post (Right Sidebar) End -->
                
            </div>
         </div>
      </div>
    
    
    
    <!-- Back to Top Start -->
    <a href="#" class="scroll-to-top"><i class="fa fa-long-arrow-up"></i></a>
    <!-- Back to Top End -->
    
    
    <!-- All Javascript Plugins  -->
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugin.js' %}"></script>
    
    <!-- Main Javascript File  -->
    <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>

    
   </body>
 </html>